#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header) 
name: AWS Blog

# Short bio or description (displayed in the header)
description: with focus on aws-cli 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/fschaeffler.png

certificate-csaa: /images/csaa-logo.png
certificate-csaa-link: https://aws.amazon.com/certification/certified-solutions-architect-associate

#
# Flags below are optional...
#

# Language of blog content
language: en

# Includes an icon in the footer for each username you enter
footer-links:
  email: flo@aws-blog.io
  github: fschaeffler
  xing: Florian_Schaeffler3
  linkedin: fschaeffler
  rss: true
  stackoverflow: "users/3249481/fschaeffler"
  facebook: awsblogio
  twitter: aws_blog_io

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: flo-aws-blog

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-63060326-1

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: http://aws-blog.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: pygments
permalink: /:year/:title/

# The release of Jekyll Now that you're using
version: v2.5.3

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - octopress-minify-html

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
    - images/raw/
    - _deploy/_deploy.sh
    - _deploy/_deploy-staging.sh
    - _deploy/_deploy-production.sh
    - _dev/
    - images/aws-icons/100x100/stylesheet.txt
    - images/aws-icons/40x40/stylesheet.txt
